### ISSUE TITLE
Troubleshoot issue with publishing 2022 cached imagery

### ISSUE THREAD

**Issue by David-Yarnell** [Innovate-Inc/Frederick-CO#108]
Cache: F:\arcgisserver\Aerial_2022

Has been published but when trying to view the service the imagery is not available but if you add the cache is seems as though the imager is there.

**Comment by eb016685** [comment]
Investigated issue and it appears that the cached tiles aren't available for Aerial 2022 imagery service. I recreated the tile cache with the geoprocessing tool and it didn't complete successfully and only displaying a few cached tiles. This may be due to low disk space or another underlying issue with the way it was published.
I would suggest having the rasters available on the tlweb05 server in a mosaic dataset to try and publish with ArcMap

**Comment by ckamigaki** [comment]
Disk space has been expanded.  I can look at moving the mosaic over to the server.

Cindy Kamigaki
GIS Manager | she, her, hers
Town of Frederick | 720.382.5653
***@***.******@***.***> | FrederickCO.gov<http://www.frederickco.gov/>
[Email sig logo4]<http://www.frederickco.gov/>









________________________________

**Comment by ckamigaki** [comment]
I was able to move the mosaic over to the TLWeb05 server.  F:\Web\F\GIS.FrederickCO.gov\ESRI\Aerial2022.gbd

Can you please try again.

Cindy Kamigaki
GIS Manager | she, her, hers
Town of Frederick | 720.382.5653
***@***.******@***.***> | FrederickCO.gov<http://www.frederickco.gov/>
[Email sig logo4]<http://www.frederickco.gov/>









________________________________

**Comment by eb016685** [comment]
I've started the conversion of those rasters to .jp2 and will publish after the process is finished
